before_install:
  - cd ~
install:
  - git clone git://github.com/n1k0/casperjs.git
  - sudo ln -s $PWD/casperjs/bin/casperjs /usr/local/bin/casperjs
  - gem install rack
  - gem install jekyll
before_script:
  - cd $TRAVIS_BUILD_DIR
  - jekyll build
  - rackup -D
script:
  - casperjs test _tests
